### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by nullrndtx** [Screetsec/Dracnmap#1]
./Dracnmap: 115: ./Dracnmap: Syntax error: "(" unexpected

![Syntax Error](http://i.imgur.com/kVniFGF.png)

Operating System:
- BackBox 4.6
- Bash Version 4.3-7ubuntu1.5

**Comment by screetsec** [comment]
sudo ./Dracnmap.sh or sudo su ./Dracnmap.sh 

wkwkwk :p

**Comment by rafeyu** [comment]
Ikut nimbrung ..

Maybe add `if [ $EUID -ne 0 ]; then exit 1; fi` stuff

:D 

Edit: oops, already there ..

**Comment by screetsec** [comment]
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

leh ugha ahahah

**Comment by screetsec** [comment]
FIXED

**Comment by ehriman** [comment]
where we add this [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@" ?
