### ISSUE TITLE
Checking the Nmap commands

### ISSUE THREAD

**Issue by trimstray** [Screetsec/Dracnmap#16]
Release: **[testing](https://github.com/trimstray/Dracnmap/tree/testing)**
Type: **bug**

Checking if all work correctly.

Example:

- webservice module: 1 menu entry
``````
Failed to resolve "firewall-bypass.targetport=22".
``````

**Comment by screetsec** [comment]
The feature and idea from [@rimstray](https://github.com/trimstray), implement on their tools sandmap 

https://github.com/trimstray/sandmap
