### ISSUE TITLE
Validation of the entered data

### ISSUE THREAD

**Issue by trimstray** [Screetsec/Dracnmap#17]
Release: **[testing](https://github.com/trimstray/Dracnmap/tree/testing)**
Type: **bug**

Add of a mechanism checking the entered data from the CLI (for `set` command).

Example:

``````
Screetsec@dracnmap> set session ipaddr
What is your IP Target or Host: i_am_to_the_correct_hostname
Screetsec@dracnmap> show session ipaddr
{"IP address":
  {"ipaddr":"i_am_to_the_correct_hostname"}
}
``````

**Comment by screetsec** [comment]
The feature and idea from [@rimstray](https://github.com/trimstray), implement on their tools sandmap 

https://github.com/trimstray/sandmap
