### ISSUE TITLE
Save session keys

### ISSUE THREAD

**Issue by trimstray** [Screetsec/Dracnmap#19]
Release: **[testing](https://github.com/trimstray/Dracnmap/tree/testing)**
Type: **feature**

Save session keys to config file.

At this time:
- show session keys/options:
``````
show session <key>
``````
- set session keys/options:
``````
set session <key>
``````

**Comment by screetsec** [comment]
The feature and idea from [@rimstray](https://github.com/trimstray), implement on their tools sandmap 

https://github.com/trimstray/sandmap
