### ISSUE TITLE
Store Nmap commands in json file

### ISSUE THREAD

**Issue by trimstray** [Screetsec/Dracnmap#20]
Release: **[testing](https://github.com/trimstray/Dracnmap/tree/testing)**
Type: **feature**

Storing all available Nmap commands from the CLI level in the json file (or anything else that is easily parsed using bash). Addition of the loading mechanism to relevant entries for a specific menu.

**Comment by screetsec** [comment]
The feature and idea from [@rimstray](https://github.com/trimstray), implement on their tools sandmap 

https://github.com/trimstray/sandmap
