### ISSUE TITLE
Multiple scan - improved support for multiple IP addresses

### ISSUE THREAD

**Issue by trimstray** [Screetsec/Dracnmap#23]
Release: **[testing](https://github.com/trimstray/Dracnmap/tree/testing)**
Type: **feature**
Status: **to_closed**

Improved support for multiple IP addresses. At this time multiple scanning is disabled.

**Comment by screetsec** [comment]
The feature and idea from [@rimstray](https://github.com/trimstray), implement on their tools sandmap 

https://github.com/trimstray/sandmap
