### ISSUE TITLE
Pass the nmap process to a separate terminal

### ISSUE THREAD

**Issue by trimstray** [Screetsec/Dracnmap#24]
Release: **[testing](https://github.com/trimstray/Dracnmap/tree/testing)**
Type: **feature**

Pass the nmap process to a separate terminal (option to restore from **v2.2**).

**Comment by screetsec** [comment]
The feature and idea from [@rimstray](https://github.com/trimstray), implement on their tools sandmap 

https://github.com/trimstray/sandmap
