### ISSUE TITLE
Creating mass scans

### ISSUE THREAD

**Issue by trimstray** [Screetsec/Dracnmap#26]
Release: **[testing](https://github.com/trimstray/Dracnmap/tree/testing)**
Type: **feature**
Status: **open**

Adding a mass scanning mechanism using a set of similar scenarios. For example:
```
[21] mysql-dump-hashes
[22] mysql-empty-password
[23] mysql-query
[24] mysql-users
```

Creating on this basis one scan performing all available options for each type.

**Comment by screetsec** [comment]
The feature from [@rimstray](https://github.com/trimstray), implement on their tools sandmap 

https://github.com/trimstray/sandmap
