### ISSUE TITLE
Dracnmap is Not working !!

### ISSUE THREAD

**Issue by kali64amd** [Screetsec/Dracnmap#27]
Hi, there

OS - Kali

Any Idea why I'm getting this error?? 

 Screetsec@dracmap-v2: 3

  What is your IP Target or Host: xxx.xxx.x.xx
  Do you want exit? ( Yes / No ) :./dracnmap-v2.2-dracOs.sh: line 3065: urxvt: command not found

./dracnmap-v2.2-dracOs.sh: line 3121: [: !=: unary operator expected
./dracnmap-v2.2-dracOs.sh: line 3125: [: !=: unary operator expected

Appreciate you'r input

**Comment by screetsec** [comment]
first install urxvt
sudo apt-get install rxvt-unicode
