### ISSUE TITLE
Dracnmap.sh: 120: Dracnmap.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by watchix** [Screetsec/Dracnmap#3]
I've just cloned from GIT, chmod +x Dracnmap.sh, runed it as root and get this error :

-e \e[0;36m 
             .-.____________________.-. 
      ___ _.' .-----.    _____________|======+----------------+ 
     /_._/   (      |   /_____________|      |      OOO       | 
       /      '  _ ____/                     |  BOOOMM !!!!!! | 
      |_      .( \                          |________________| 
     .'  @-._/____// 
   .'       |=== 
   /        / 
  /        | 
  |        ' 
  |         \ 
   -._____./ 

-e \e[1;32m-- -- +=[(c) 2016-2017 | dracos-linux.org | Linuxsec.org | Pentester Indonesia 
-e \e[0;36m-- -- +=[ Author: Screetsec < Edo Maland >  ]=+ -- -- 
-e  
[!]::[Check Dependencies]:
[✔]::[Check User]: root
[✔]::[Internet Connection]: connected!
[✔]::[ Nmap ]: installation found!
Dracnmap.sh: 120: Dracnmap.sh: Syntax error: "(" unexpected

**Comment by carlfugate** [comment]
Is there any way in Mac Terminal to get it to parse the colors?  My understanding is that Bash 3.2 thats included does not support \e but I also tried replacing with \33 however it still does not render the color codes.

**Comment by screetsec** [comment]
https://github.com/Screetsec/Dracnmap/issues/1

**Comment by nullrndtx** [comment]
@carlfugate @watchix try the latest commit, or change it by your self /bin/bash to #!/usr/bin/env bash

**Comment by carlfugate** [comment]
I had already tried changing the shell directly to /bin/bash without
success and also tried calling it directly with bash.  Ill pull the new
commit and try again.
