### ISSUE TITLE
XTERM Warning : Tried connect to session manager 

### ISSUE THREAD

**Issue by Djenova** [Screetsec/Dracnmap#7]
![dracnmap](https://cloud.githubusercontent.com/assets/7172538/19416129/5b92fcdc-93b2-11e6-8bab-13bd2e7cbd10.png)

bisa di atasi dengan `env -u SESSION_MANAGER xterm...`, Mau ngerubah codenya tapi banyak banget

**Comment by Screetsec** [comment]
sama
